### ISSUE TITLE
Forked Repos Fail to Load

### ISSUE THREAD

**Issue by rogerluan** [maoyama/GitBlamePR#38]
Hey there!

First of all, this is a great app! I definitely find myself doing these manual searches more often than I'd like to. Having a one-click action to jump to the commit and/or PR in GitHub website is definitely a time saver!

I'd like to report a bug, though: for forked repos, it tries opening the commit/PR in the forked repo instead of the original repo. It should probably be able to pick up whether the PR belongs to the original PR or one of its forks.

Thanks for all the effort to build this great tool!

**Comment by maoyama** [comment]
I haven't come up with a good solution to this issue.

However, if you change it so that Forked Repo outputs to the first line of the execution result of `git remote -v`, it should not fail.(Because it has the following code)
https://github.com/maoyama/GitBlamePR/blob/d4d8e4cbe0ef772074460a4beb5a4f59614e0e69/GitBlamePR/Domain/RepositoryURL.swift#L22-L36

**Comment by rogerluan** [comment]
That's good to know, thanks!
